baseURL = "https://harbor.mffseal.top/"
# baseURL = "http://localhost:1313/"
languageCode = "zh-cn"
DefaultContentLanguage = "cn"
googleAnalytics = "G-NV58SYWRZD"
relativeURLs = false
disablePathToLower = true
ignoreFiles = [
    "content/templates/*",
    "content/private/*",
    "content/.obsidian/*",
    "content/.trash/*",
    "content/0_0-收集/*",
    "content/0_1-私密/*",
    "content/z-oblib/z0-templates/*",
    "content/z-oblib/z1-from-templates/*",
    "content/z-oblib/z3-frames/*",
]
summaryLength = 20
paginate = 20
enableGitInfo = true

[markup]
    [markup.tableOfContents]
        endLevel = 3
        ordered = true
        startLevel = 2
    [markup.highlight]
        noClasses = false
        anchorLineNos = true
        codeFences = true
        guessSyntax = true
        hl_Lines = ""
        lineAnchors = ""
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        style = "dracula"
    [frontmatter]
        lastmod = ["updated", ":git"]
        # lastmod = [":lastmod", "updated"]
        # publishDate = ["publishDate", "updated"]
    [markup.goldmark.renderer]
        unsafe = true
